# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bccd3edfd6ab3e5553d308279682995451466c18d66eda5be1652be99a4b69fed3829a50de7e50cf4935cbdd9572dbb88b254bbd5a99c1220edcc322bb2f70aa

test:
  secret_key_base: ae0ce6cc83140073871eade6f5f7a7907cb0e26f5e17237d37cba066b366e6590cc79e9c8c7bac4b92a1ebc90b507da45f6607c21c7e106892a5689e0d2bbf66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
