# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b1648b6f41bcfe8359462979ac1da0cc8cbcac75358a44bcbeb7f8f964bce98de88cdc06ad2cbf1c604b33ec260b73679e734836c2ecfc35958918d4d675b9

test:
  secret_key_base: ffeee2cd9182af00b53a0b4ccd0f07b1875d9421ecc4d569884d52882815862f046b749369bb73b7bd6bf485c21af520e7b93512e8c184bcb23c3f0ed03c7a4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
